/*
 * JS for Tab1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '6b6ca046-473c-4601-9541-fc02f086f347';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Tab1",
    "location": "Tab1.html"
}, {
    "name": "Visualizer",
    "location": "Visualizer.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

Tab1_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_2': 'Tab1_mobilenavbar_2',
        'mobilenavbaritem_3': 'Tab1_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'Tab1_mobilenavbaritem_4',
        'mobilenavbaritem_5': 'Tab1_mobilenavbaritem_5',
        'mobilebutton_7': 'Tab1_mobilebutton_7',
        'mobilegrid_9': 'Tab1_mobilegrid_9',
        'mobilegridcell_10': 'Tab1_mobilegridcell_10',
        'mobileimage_30': 'Tab1_mobileimage_30',
        'mobilegridcell_12': 'Tab1_mobilegridcell_12',
        'mobileimage_29': 'Tab1_mobileimage_29',
        'mobilegridcell_14': 'Tab1_mobilegridcell_14',
        'mobileimage_31': 'Tab1_mobileimage_31',
        'mobilegridcell_15': 'Tab1_mobilegridcell_15',
        'mobileimage_32': 'Tab1_mobileimage_32',
        'mobilegridcell_16': 'Tab1_mobilegridcell_16',
        'mobileimage_33': 'Tab1_mobileimage_33',
        'mobilegridcell_17': 'Tab1_mobilegridcell_17',
        'mobileimage_34': 'Tab1_mobileimage_34',
        'mobilegridcell_18': 'Tab1_mobilegridcell_18',
        'mobileimage_35': 'Tab1_mobileimage_35',
        'mobilegridcell_19': 'Tab1_mobilegridcell_19',
        'mobileimage_36': 'Tab1_mobileimage_36',
        'mobilegridcell_20': 'Tab1_mobilegridcell_20',
        'mobileimage_37': 'Tab1_mobileimage_37',
        'mobilegridcell_21': 'Tab1_mobilegridcell_21',
        'mobileimage_38': 'Tab1_mobileimage_38',
        'mobilegridcell_22': 'Tab1_mobilegridcell_22',
        'mobileimage_39': 'Tab1_mobileimage_39',
        'mobilegridcell_23': 'Tab1_mobilegridcell_23',
        'mobileimage_40': 'Tab1_mobileimage_40',
        'mobilegridcell_24': 'Tab1_mobilegridcell_24',
        'mobileimage_41': 'Tab1_mobileimage_41',
        'mobilegridcell_25': 'Tab1_mobilegridcell_25',
        'mobileimage_42': 'Tab1_mobileimage_42',
        'mobilegridcell_26': 'Tab1_mobilegridcell_26',
        'mobileimage_43': 'Tab1_mobileimage_43',
        'mobilegridcell_27': 'Tab1_mobilegridcell_27',
        'mobileimage_44': 'Tab1_mobileimage_44',
        'mobilegridcell_28': 'Tab1_mobilegridcell_28',
        'mobileimage_45': 'Tab1_mobileimage_45'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Tab1';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var Tab1_beforeshow = function() {
            Apperyio.CurrentScreen = "Tab1";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Tab1_onLoad = function() {
            Tab1_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            Tab1_deviceEvents();
            Tab1_windowEvents();
            Tab1_elementsEvents();
        };

    // screen window events
    var Tab1_windowEvents = function() {

            $('#Tab1').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Tab1_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Tab1_elementsExtraJS = function() {
            // screen (Tab1) extra code

        };

    // screen elements handler
    var Tab1_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#Tab1_mobilecontainer [name="mobilebutton_7"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio('blindsPanel').panel("open");
                        //Apperyio('panel').panel( "close" );
                    }
                },
            }, '#Tab1_mobilecontainer [name="mobilebutton_7"]');

            $(document).off("click", '[name="mobileimage_30"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        alert('Tsela tun the cone maburu a tshephe');
                        Apperyio('blindsPanel').panel("close");

                    }
                },
            }, '[name="mobileimage_30"]');

        };

    $(document).off("pagebeforeshow", "#Tab1").on("pagebeforeshow", "#Tab1", function(event, ui) {
        Tab1_beforeshow();
    });

    if (runBeforeShow) {
        Tab1_beforeshow();
    } else {
        Tab1_onLoad();
    }
};

$(document).off("pagecreate", "#Tab1").on("pagecreate", "#Tab1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Tab1_js();
});