/*
 * JS for Visualizer generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '6b6ca046-473c-4601-9541-fc02f086f347';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Tab1",
    "location": "Tab1.html"
}, {
    "name": "Visualizer",
    "location": "Visualizer.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

Visualizer_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'Visualizer_mobilenavbar_6',
        'mobilenavbaritem_7': 'Visualizer_mobilenavbaritem_7',
        'mobilenavbaritem_8': 'Visualizer_mobilenavbaritem_8',
        'mobilenavbaritem_9': 'Visualizer_mobilenavbaritem_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Visualizer';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var Visualizer_beforeshow = function() {
            Apperyio.CurrentScreen = "Visualizer";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Visualizer_onLoad = function() {
            Visualizer_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            Visualizer_deviceEvents();
            Visualizer_windowEvents();
            Visualizer_elementsEvents();
        };

    // screen window events
    var Visualizer_windowEvents = function() {

            $('#Visualizer').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Visualizer_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Visualizer_elementsExtraJS = function() {
            // screen (Visualizer) extra code

        };

    // screen elements handler
    var Visualizer_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#Visualizer_mobileheader [name="mobilenavbaritem_7"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('Tab1', {
                            reverse: false
                        });

                    }
                },
            }, '#Visualizer_mobileheader [name="mobilenavbaritem_7"]');

        };

    $(document).off("pagebeforeshow", "#Visualizer").on("pagebeforeshow", "#Visualizer", function(event, ui) {
        Visualizer_beforeshow();
    });

    if (runBeforeShow) {
        Visualizer_beforeshow();
    } else {
        Visualizer_onLoad();
    }
};

$(document).off("pagecreate", "#Visualizer").on("pagecreate", "#Visualizer", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Visualizer_js();
});